version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: ddd-demo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ddd_demo
      MYSQL_USER: ddd_user
      MYSQL_PASSWORD: ddd_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - ddd-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: ddd-demo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ddd-network

volumes:
  mysql_data:
  redis_data:

networks:
  ddd-network:
    driver: bridge