# Rose Redis Spring Boot Starter 默认配置
rose:
  redis:
    # 是否启用 Redis 增强功能
    enabled: true
    
    # 分布式锁配置
    lock:
      # 是否启用分布式锁
      enabled: true
      # 默认锁超时时间（毫秒）
      default-timeout: 30000
      # 是否启用自动续期
      auto-renewal: true
      # 续期间隔时间（毫秒）
      renewal-interval: 10000
      # 锁 key 前缀
      key-prefix: "rose:lock:"
      # 最大等待时间（毫秒）
      max-wait-time: 5000
    
    # 缓存增强配置
    cache:
      # 是否启用缓存增强功能
      enabled: true
      # 是否启用多级缓存
      multi-level: true
      # 是否启用缓存穿透防护
      penetration-protection: true
      # 是否启用缓存预热
      warmup-enabled: false
      # 缓存 key 前缀
      key-prefix: "rose:cache:"
      # 布隆过滤器预期插入数量
      bloom-filter-expected-insertions: 1000000
      # 布隆过滤器误判率
      bloom-filter-false-positive-probability: 0.01
    
    # 限流配置
    rate-limit:
      # 是否启用限流功能
      enabled: true
      # 默认限流许可数
      default-permits: 100
      # 时间窗口大小（秒）
      window-size: 60
      # 限流 key 前缀
      key-prefix: "rose:rate:"
      # 默认限流算法（TOKEN_BUCKET, SLIDING_WINDOW）
      default-algorithm: TOKEN_BUCKET
    
    # 消息队列配置
    message:
      # 是否启用消息队列功能
      enabled: true
      # 是否启用 Redis Stream
      stream-enabled: true
      # 是否启用延迟消息
      delayed-enabled: true
      # 消息 key 前缀
      key-prefix: "rose:msg:"
      # 默认消费者组名
      default-consumer-group: "rose-group"
      # 死信队列 key 前缀
      dead-letter-prefix: "rose:dlq:"
      # 最大重试次数
      max-retry-count: 3
    
    # 会话管理配置
    session:
      # 是否启用会话管理
      enabled: true
      # 会话超时时间（秒）
      timeout: 1800
      # 会话 key 前缀
      key-prefix: "rose:session:"
      # 是否启用会话事件监听
      event-listener-enabled: true
    
    # 数据结构操作配置
    data-structure:
      # 是否启用数据结构增强操作
      enabled: true
      # 批量操作的默认批次大小
      default-batch-size: 100
      # 是否启用 Pipeline 优化
      pipeline-enabled: true
      # Pipeline 批次大小
      pipeline-batch-size: 100