version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
    ignore:
      # 忽略所有主要、次要版本更新
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor