version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8
    container_name: iot-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: iot_platform
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: iot_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./iot-starter/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: iot-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

  # RabbitMQ消息队列
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: iot-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      timeout: 20s
      retries: 10

  # EMQ X MQTT Broker
  emqx:
    image: emqx/emqx:5.0
    container_name: iot-emqx
    environment:
      EMQX_NAME: emqx
      EMQX_HOST: localhost
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "18083:18083"
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "emqx_ctl", "status"]
      timeout: 20s
      retries: 10

  # InfluxDB时序数据库
  influxdb:
    image: influxdb:2.7
    container_name: iot-influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpassword
      DOCKER_INFLUXDB_INIT_ORG: iot_org
      DOCKER_INFLUXDB_INIT_BUCKET: iot_bucket
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: iot_token
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "influx", "ping"]
      timeout: 20s
      retries: 10

  # IoT平台应用
  iot-platform:
    build: .
    container_name: iot-platform
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: iot_platform
      DB_USERNAME: root
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      MQTT_HOST: emqx
      MQTT_PORT: 1883
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      emqx:
        condition: service_healthy
      influxdb:
        condition: service_healthy
    networks:
      - iot-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/iot/actuator/health"]
      timeout: 30s
      retries: 5
      start_period: 60s

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
  emqx_data:
  emqx_log:
  influxdb_data:

networks:
  iot-network:
    driver: bridge