server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

spring:
  datasource:
    url: jdbc:mysql://localhost:${MYSQL_PORT:3306}/${MYSQL_DATABASE:todo}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ${MYSQL_ROOT_PASSWORD:password}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  cache:
    type: redis
    redis:
      time-to-live: 6h
  data:
    redis:
      host: localhost
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: [ health, info, metrics ]
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

app:
  mybatis:
    pagination:
      max-page-size: 100
