services:
  mysql:
    image: mysql:8
    container_name: rose-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rose123456
      MYSQL_DATABASE: rose
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./rose-server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  redis:
    image: redis:6.2
    container_name: rose-redis
    ports:
      - "6379:6379"
    restart: always
    command: [ "redis-server", "--appendonly", "yes" ]

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rose-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"