services:
  rose-mysql:
    image: mysql:8
    container_name: rose-mysql
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: rose
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
    ports:
      - "3306:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD:-password}"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    volumes:
      - ./rose-application/src/main/resources/iam-schema.sql:/docker-entrypoint-initdb.d/iam-schema.sql:ro

  rose-redis:
    image: redis:7-alpine
    container_name: rose-redis
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 20s
      retries: 10

  rose-rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rose-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always


  rose-mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: rose-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"