spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rose?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  messages:
    encoding: UTF-8
    basename: classpath:messages
  mail:
    host: 127.0.0.1
    port: 1025
    username: PLACEHOLDER
    password: PLACEHOLDER
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    io.github.rose: debug
