spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rose?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: 127.0.0.1
    port: 1025
    username: PLACEHOLDER
    password: PLACEHOLDER
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
