spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd_demo_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    
  redis:
    host: localhost
    port: 6379
    database: 1

logging:
  level:
    com.example.ddddemo: debug
    org.springframework.web: debug