spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd_demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    
  data:
    redis:
      host: localhost
      database: 1
      port: 6379

logging:
  level:
    com.example.ddddemo: debug
    org.springframework.web: debug