spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd_demo_test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    
  redis:
    host: localhost
    port: 6379
    database: 2

logging:
  level:
    com.example.ddddemo: info