# 开发环境配置
spring:
  # 数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/iot_platform_dev?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: password
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 0
  
  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 日志配置
logging:
  level:
    io.github.rose.iot: DEBUG
    org.springframework.security: DEBUG
    com.baomidou.mybatisplus: DEBUG
    com.alibaba.druid: DEBUG

# IoT平台配置
iot:
  # MQTT配置
  mqtt:
    broker-url: tcp://localhost:1883
  
  # 数据存储配置
  data:
    retention-days: 30
    compression-enabled: false
    batch-size: 100