rose:
  crypto:
    # 是否启用字段加密
    enabled: true
    # 加密密钥（生产环境应该从外部配置获取）
    secret-key: "0123456789abcdeffedcba9876543210"
    # 加密失败时是否抛出异常
    fail-on-error: true

    # 监控配置
    metrics:
      # 是否启用指标收集
      enabled: true
      # 指标前缀
      prefix: "crypto"
      # 是否包含详细的算法统计
      include-algorithm-details: true
      # 是否包含数据大小分布统计
      include-data-size-distribution: true
      # 是否包含成功率统计
      include-success-rate: true

    # 健康检查配置
    health:
      # 是否启用健康检查
      enabled: true
      # 健康检查超时时间（毫秒）
      timeout: 5000
      # 测试数据
      test-data: "health-check-test"
      # 是否在健康检查中包含性能统计
      include-performance-stats: true
      # 成功率阈值（低于此值将标记为不健康）
      success-rate-threshold: 95.0
      # 错误数量阈值（超过此值将标记为不健康）
      error-count-threshold: 100

    # 缓存配置
    cache:
      # 是否启用统计缓存
      enabled: true
      # 缓存清理间隔（秒）
      cleanup-interval: 3600
      # 最大缓存条目数
      max-entries: 10000

    # 哈希配置
    hash:
      # 是否启用哈希功能
      enabled: true
      # 全局盐值（生产环境应该从外部配置获取）
      global-salt: "rose-mybatis-global-salt-2024"
      # 默认哈希算法
      algorithm: "HMAC_SHA256"
      # HMAC 密钥（生产环境应该从外部配置获取）
      hmac-key: "rose-mybatis-hmac-key-2024"

# Spring Boot Actuator 配置（可选）
management:
  endpoints:
    web:
      exposure:
        # 暴露的端点
        include: health,info,metrics,crypto
      base-path: /actuator
  endpoint:
    crypto:
      # 是否启用加密监控端点
      enabled: true
      # 是否需要认证
      sensitive: true