spring:
  application:
    name: test-security-app

server:
  port: 8082

# Rose Security 配置
rose:
  security:
    enabled: true
    login-path: /api/auth/login
    logout-path: /api/auth/logout
    refresh-path: /api/auth/refresh
    base-path: /api/**
    permit-paths:
      - /health
      - /info
      - /api/auth/login
      - /api/auth/logout
      - /api/auth/refresh

# 日志配置
logging:
  level:
    root: INFO
    io.github.rosestack.spring.boot.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
