spring:
  web:
    locale: zh_CN
    locale-resolver: accept_header
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: PT1H
  # Jackson 序列化配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
      indent-output: false
    deserialization:
      fail-on-unknown-properties: false
      accept-empty-string-as-null-object: true

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO
  #    com.baomidou.mybatisplus.core.mapper: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

rose:
  web:
    # 是否启用 Web 功能
    enabled: true

    # 全局排除路径配置
    # 这些路径将被所有过滤器排除，不进行过滤处理
    global-exclude-paths:
      - "/actuator/**"
      - "/swagger-ui/**"
      - "/v3/api-docs/**"
      - "/webjars/**"
      - "/favicon.ico"
      - "/error"
      - "/static/**"
      - "/public/**"

    # 过滤器配置
    filter:
      # 请求ID过滤器
      request-id:
        enabled: true
      # XSS过滤器
      xss:
        enabled: true
        excludePaths:
          - /swagger-ui.html
          - /swagger-resources/**
          - /v3/api-docs
          - /swagger-ui/**
          - /actuator/**

      caching-request:
        enabled: true

    swagger:
      enabled: true


